version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api

  api:
    image: your-api-image:latest  # Replace with your actual API image
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    # Add any API-specific environment variables here

networks:
  default:
    name: rag-patient-chatbot-network
